baseURL = 'https://yesjinu.github.io/'
languageCode = 'ko-KR'
title = 'Dent in the universe'
theme = "PaperMod"

paginate = 5
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
googleAnalytics = "UA-123-45"
pygmentsUseClasses = true

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "ExampleSite"
description = "ExampleSite description"
keywords = [ "Blog", "Portfolio", "PaperMod" ]
#author = "Me"
images = [ "<link or path of image for opengraph, twitter-cards>" ]
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
#ShowShareButtons = true
#ShowPostNavLinks = true
#ShowBreadCrumbs = true
ShowCodeCopyButtons = true
#ShowWordCount = true
ShowRssButtonInSectionTermList = true
#UseHugoToc = true
#disableSpecial1stPost = false
disableScrollToTop = true
comments = false
hidemeta = false
hideSummary = false
#showtoc = true
#tocopen = false

[params.assets]
favicon = "<link / abs url>"
favicon16x16 = "<link / abs url>"
favicon32x32 = "<link / abs url>"
apple_touch_icon = "<link / abs url>"
safari_pinned_tab = "<link / abs url>"

[params.label]
text = "Home"
icon = "/apple-touch-icon.png"
iconHeight = 35

[params.profileMode]
enabled = false
title = "ExampleSite"
subtitle = "This is subtitle"
imageUrl = "<img location>"
imageWidth = 120
imageHeight = 120
imageTitle = "my image"

[[params.profileMode.buttons]]
name = "Posts"
url = "posts"

[[params.profileMode.buttons]]
name = "Tags"
url = "tags"

[params.homeInfoParams]
Title = "Take chances, make mistakes, get messy."
#Content = "Welcome to my blog"

[[params.socialIcons]]
name = "cv"
url = "https://bit.ly/about_jinu"


[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/jinu-noh-59a770185/"

[[params.socialIcons]]
name = "github"
url = "https://github.com/yesjinu/"

[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1_000
threshold = 0.4
minMatchCharLength = 0
keys = [ "title", "permalink", "summary", "content" ]

[[menu.main]]
identifier = "categories"
name = "categories"
url = "/categories/"
weight = 10

[[menu.main]]
identifier = "tags"
name = "tags"
url = "/tags/"
weight = 20

[markup.highlight]
noClasses = false
